# Generated by Django 2.2.7 on 2024-07-24 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Enter Product Stock Keeping Unit', max_length=13)),
                ('barcode', models.CharField(help_text='Enter Product Barcode (ISBN, UPC ...)', max_length=13)),
                ('title', models.CharField(help_text='Enter Product Title', max_length=200)),
                ('description', models.TextField(help_text='Enter Product Description')),
                ('unit_cost', models.FloatField(help_text='Enter Product Unit Cost')),
                ('unit', models.CharField(help_text='Enter Product Unit ', max_length=10)),
                ('quantity', models.FloatField(help_text='Enter Product Quantity')),
                ('min_quantity', models.FloatField(help_text='Enter Product Min Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Enter Product Stock Keeping Unit', max_length=13)),
                ('barcode', models.CharField(help_text='Enter Product Barcode (ISBN, UPC ...)', max_length=13)),
                ('comment', models.TextField(help_text='Enter Product Stock Keeping Unit')),
                ('unitCost', models.FloatField(help_text='Enter Product Unit Cost')),
                ('quantity', models.FloatField(help_text='Enter Product Quantity')),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, choices=[('import', 'New Stock'), ('order_placed', 'Order Placed'), ('order_canceled', 'Order Canceled')], default='ns', help_text='Reason for transaction', max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
